MyDev/src/objects/JobPostingCite__c.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>JobPostingCite</label>
    <nameField>
        <displayFormat>JOBSITE-{0000}</displayFormat>
        <label>JobPostingSite Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>JobPostingCites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDev/src/objects/StrikeIronInfo__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <inlineHelpText>the password registered with StrikeIron</inlineHelpText>
        <label>Password</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userID__c</fullName>
        <inlineHelpText>the email address registered with StrikeIron</inlineHelpText>
        <label>User ID</label>
        <type>Email</type>
    </fields>
    <label>StrikeIronInfo</label>
    <nameField>
        <displayFormat>SI-{00}</displayFormat>
        <label>StrikeIronInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>StrikeIronInfos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDev/src/classes/SOAIpLookup.cls
public class SOAIpLookup {

    public JobPostingCite__c jobSite {get;set;}
    public ApexPages.standardController controller {get;set;}
    public String ipaddress {get;set;}
    private StrikeIronInfo__c info {
        get{
            if (info == null) {
                info = [select userid__c,password__c from strikeironinfo__c limit 1];
            }
            return info;    
        }
        set;
    }
    
    public SOAIpLookup(ApexPages.StandardController stdController) {
        // constructor
        controller = stdController;
        this.jobSite = (JobPostingCite__c)stdController.getRecord();      
    }
    
    public PageReference strikeIronIpCheck(){
        // Create the stub
        StrikeIronIPLookup.IPAddressLookupSoap dns = new StrikeIronIPLookup.IPAddressLookupSoap();

        // Set up the license header
        dns.LicenseInfo = new strikeiron.LicenseInfo();
        dns.LicenseInfo.RegisteredUser = new strikeiron.RegisteredUser();
        dns.LicenseInfo.RegisteredUser.UserID = info.userid__c;
        dns.LicenseInfo.RegisteredUser.Password = info.password__c;
        // Make the Web service call
        StrikeIronIPLookup.SIWsOutputOfDNSInfo info = dns.DNSLookup(jobSite.URL__c);
        System.debug(info);
        ipaddress = info.ServiceResult.HostName;
        
        return null;
    }
}