MyDev/src/objects/Mailing_List__c.object
<CustomObject>
    <fields>
        <fullName>MailingListName__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>MailingListName</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Users__c</fullName>
        <label>Users</label>
        <type>TextArea</type>
    </fields>
    <label>Mailing List</label>
    <nameField>
        <displayFormat>ml-{0000}</displayFormat>
        <label>Mailing List Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mailing Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDev/src/classes/SSEChatterList.cls
public class SSEChatterList {
    
    public String mailingListName{set; get;}
    public String vfMailingListName{set; get;}
    public String memName { get; set; }
    public String finalList{set;get;}
    public boolean showFlag{get;set;}
    
    public SSEChatterList(){
        showFlag = false;
    }
    
    public PageReference addUser() {
        
        finalList = finalList+memName+',' ;
        memName ='';
       
        return null;
    }
    
    public PageReference SaveList() {
        
        vfMailingListName = mailingListName;
    
        Mailing_List__c m2 = new Mailing_List__c();
        m2.MailingListName__c = mailingListName;
        m2.Users__c = finalList;            
        try{
            insert m2;  
        }catch(Exception e){
        
        }    
        showFlag = true;
        
        mailingListName = '';
        finalList='';
        
        
        return null;
    }

    
}