MyDev/src/objects/Mailing_List__c.object
<CustomObject>
    <fields>
        <fullName>MailingListName__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>MailingListName</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Users__c</fullName>
        <label>Users</label>
        <type>TextArea</type>
    </fields>
    <label>Mailing List</label>
    <nameField>
        <displayFormat>ml-{0000}</displayFormat>
        <label>Mailing List Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mailing Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDev/src/classes/HelloWorldTestClass.cls
@isTest 
private class HelloWorldTestClass {
    static testMethod void validateHelloWorld() {
        User u = [select id from User where alias='KKarn'];
        System.runAs(u) {

        
            Mailing_List__c ml = new Mailing_List__c ();
            ml.MailingListName__c = '#Testing';
            ml.users__c = 'Krishna Teja Karnam,Chaitanya Krishna';
            insert ml;
            
            feedItem fi = new feedItem();
            fi.body = 'Testing #Testing Chatter Mailing List';
            fi.parentId = Userinfo.getUserId();
            
            insert fi;
            
            List<String> parts = new List<String>();
            parts.add('Krishna Teja Karnam');
            parts.add('Chaitanya Krishna');
            testAtMention.insertAtMen(parts,fi.body,fi.id);   
        
        
        }
    }
}