MyDev/src/objects/Patient__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProviderName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProviderName</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients</relationshipLabel>
        <relationshipName>Patients</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimeSlot__c</fullName>
        <label>TimeSlot</label>
        <type>Date</type>
    </fields>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MyDev/src/classes/PatientData.cls
global with sharing class PatientData {
public String imgid { get; set; }
public static String imgid1{get;set;}
public  boolean show{get;set;}
public Static String pd{get;set;}
public List<Patient__c> plist1{get;set;}
public List<Patient__c> plist{get;set;}

  public PatientData()
  {  plist=[select FirstName__c,LastName__c,TimeSlot__c,ProviderName__r.Name from Patient__c];
  
    
  
  } 
  
  
    public PageReference getData() {
    String pid=ApexPages.currentPage().getParameters().get('pid');
    Attachment att=[select id,Name from Attachment where parentId=:pid];
       imgid1=att.id;
    System.debug('pid is'+pid);
    plist1=[select FirstName__c,LastName__c,TimeSlot__c,ProviderName__r.Name from Patient__c where id=:pid];
    
        return null;
    }
    
    @RemoteAction
    global static void getPatient(String pid)
    {
       pd=pid;
       System.debug('----------'+pd);
       
      
    }
  
  

}